apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4ked
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-4ked@sha256:7f11d920484139d71aa59a705a772e2d7c838b61ea72dcb3cc6235103201766c
        name: my-nodejs
        resources: {}
status: {}
